export const DEFAULT_AWTRIX_URL = "http://192.168.100.159";
export const DEFAULT_AWTRIX_TIMEOUT_MS = 750;

export const MESSAGES = [
	"michael, let's burn more tokens",
	"burn, burn, burn",
	"umm, yummy tokens",
	"tokens fuel the thinking",
	"another turn, another token",
	"agent at work",
	"the context must grow",
	"keep the models humming",
	"fresh tokens, hot context",
	"prompt. think. repeat.",
	"more tokens for the machine",
	"an agent never rests",
	"work, work, workflow",
	"feed the language model",
	"context window says yum",
	"let the agent cook",
	"one more inference",
	"reasoning complete",
	"tokens go brrr",
	"summon the subagents",
	"the model demands context",
	"delegate and conquer",
	"ship it, little agent",
	"autocomplete destiny",
	"prompt harder",
	"deep work, deeper context",
	"inference tastes delicious",
	"agent mode complete",
	"crunch those tokens",
	"the worktree is calling",
	"commit, push, repeat",
	"just one more prompt",
	"llm, take the wheel",
	"thinking costs tokens",
	"busy agents, happy humans",
	"context is everything",
	"a token for your thoughts",
	"the agent had a plan",
	"tools out, tokens in",
	"productivity generated",
	"synthetic thoughts delivered",
	"the work is done",
	"no task too token-heavy",
	"model says: shipped",
	"tiny prompts, big dreams",
	"another job well prompted",
	"agents assemble",
	"burn tokens, ship software",
	"work smarter, prompt harder",
	"may the context be with you",
	"stack traces fear this agent",
	"cache warm, model ready",
	"another prompt bites the dust",
	"code in, confidence out",
	"pixels powered by tokens",
	"inference engine engaged",
	"context loaded, go time",
	"tiny token, mighty output",
	"agent says job done",
	"prompt accepted, code emitted",
	"ship happens",
	"merge conflicts defeated",
	"tests green, tokens gone",
	"compile first, ask later",
	"the model made it so",
	"keyboard meets cognition",
	"context window wide open",
	"another branch bears fruit",
	"tokens became software",
	"semicolons survived",
	"the diff looks delicious",
	"one prompt closer to done",
	"agents love a clean build",
	"commit energy detected",
	"lint, test, celebrate",
	"code cooked to perfection",
	"prompt power activated",
	"the model found a way",
	"syntax errors eliminated",
	"subagent reporting success",
	"reasoning has landed",
	"software by statistical magic",
	"token furnace online",
	"context acquired",
	"machine thoughts complete",
	"another artifact shipped",
	"the codebase says thanks",
	"all systems prompted",
	"hot tokens, cool code",
	"the agent understood the assignment",
	"another task vaporized",
	"prompts in, progress out",
	"code generated responsibly",
	"context served fresh",
	"the machine has spoken",
	"one more green check",
	"workflow velocity achieved",
	"token budget well spent",
	"logic locked and loaded",
	"the branch is blooming",
	"model output secured",
	"tool calls complete",
	"agents at full throttle",
	"cognition on demand",
	"prompt engineering complete",
	"codebase upgraded",
	"build passed, vibes high",
	"tokens transformed",
	"another problem compressed",
	"commit candidate ready",
	"source code summoned",
	"context conquered",
	"agent loop complete",
	"model magic, human intent",
	"tests approve this message",
	"software emerged",
	"the prompt paid off",
	"reasoning engine cooled",
	"diff delivered",
	"no tokens left behind",
	"the code is alive",
	"automated thought successful",
	"agent mission accomplished",
	"another TODO retired",
	"pixels report success",
	"inference complete, captain",
	"context goes in circles",
	"ship shape and tokenized",
	"the machine chose semicolons",
	"code crafted by context",
	"task reduced to done",
	"token-powered craftsmanship",
	"prompts are the new coffee",
	"no bug left unprompted",
	"compiler appeased",
	"branch ready for takeoff",
	"merge queue incoming",
	"clean code, dirty token bill",
	"the agent earned a break",
	"context switched successfully",
	"another function found purpose",
	"code review bait prepared",
	"the tests demand tribute",
	"logic deployed locally",
	"model momentum maintained",
	"prompt stack cleared",
	"agent work product ready",
	"terminal victory achieved",
	"software, freshly inferred",
	"all prompts lead to code",
	"the context was sufficient",
	"token sparks flying",
	"another loop terminated",
	"machine intuition delivered",
	"code complete enough to ship",
	"the agent did the typing",
	"prompt-driven development",
	"context makes the code grow",
	"synthetic focus achieved",
	"the model chose wisely",
	"task complete, cache intact",
	"full stack, full context",
	"tokens entered production",
	"branch prediction successful",
	"source assembled",
	"tests fed and happy",
	"another diff enters history",
	"agentic energy released",
	"prompt queue drained",
	"reasoning pipeline complete",
	"software forged in context",
	"machine muse reporting",
	"code path illuminated",
	"the tokens knew what to do",
	"build green, context lean",
	"another bug became lore",
	"model output, human approved",
	"prompts moved the needle",
	"toolchain says yes",
	"context reached critical mass",
	"this code has token energy",
	"agent finished with flair",
	"no TODO survives forever",
	"compile gods satisfied",
	"the model stuck the landing",
	"tokens converted to commits",
	"prompt velocity maximized",
	"another branch tamed",
	"inference with benefits",
	"code arrived just in time",
	"the agent closed the loop",
	"context delivered results",
	"syntax shaped by statistics",
	"another build earns green",
	"prompts keep shipping",
	"model-made momentum",
	"codebase leveled up",
	"token economy booming",
	"task done, onward",
	"context consumed, value created",
] as const;

export interface DisplayMessageOptions {
	baseUrl?: string;
	fetchImpl?: typeof fetch;
	timeoutMs?: number;
}

export function randomMessage(random = Math.random): string {
	return MESSAGES[Math.floor(random() * MESSAGES.length)] ?? MESSAGES[0];
}

export function normalizeAwtrixUrl(value: string | undefined): string | undefined {
	if (value === "") return undefined;
	const url = value ?? DEFAULT_AWTRIX_URL;
	const withProtocol = /^https?:\/\//i.test(url) ? url : `http://${url}`;
	return withProtocol.replace(/\/+$/, "");
}

export function isQuietHours(date = new Date(), start = 20, end = 8): boolean {
	const hour = date.getHours();
	return hour >= start || hour < end;
}

export async function tryDisplayMessage(
	message: string,
	options: DisplayMessageOptions = {},
): Promise<boolean> {
	const baseUrl = normalizeAwtrixUrl(options.baseUrl ?? process.env.AWTRIX_URL);
	if (!baseUrl) return false;

	const controller = new AbortController();
	const timeout = setTimeout(
		() => controller.abort(),
		options.timeoutMs ?? DEFAULT_AWTRIX_TIMEOUT_MS,
	);

	try {
		const response = await (options.fetchImpl ?? fetch)(`${baseUrl}/api/notify`, {
			method: "POST",
			headers: { "content-type": "application/json" },
			body: JSON.stringify({
				text: message.toLowerCase(),
				textCase: 2,
				center: false,
				repeat: 1,
				duration: 5,
				stack: false,
				scrollSpeed: 100,
			}),
			signal: controller.signal,
		});
		return response.ok;
	} catch {
		return false;
	} finally {
		clearTimeout(timeout);
	}
}
